In [1]:
import torch

In [2]:
and_data = torch.tensor([ [0, 0],
                          [0, 1],
                          [1, 0],
                          [1, 1]], dtype=torch.float32)
and_labels = torch.tensor([ [1],
                            [1],
                            [1],
                            [0]], dtype=torch.float32)

In [3]:
import numpy as np

np.random.randn(3, 224, 224).shape

(3, 224, 224)

In [4]:
import torch.nn as nn

l1 = nn.Linear(2, 1)
x = l1(and_data)
print(x.shape)
torch.relu(x)

act_fn = nn.ReLU()
act_fn(x)

torch.Size([4, 1])


tensor([[0.4620],
        [0.6315],
        [0.6408],
        [0.8103]], grad_fn=<ReluBackward0>)

In [5]:
l1.weight, l1.bias, l1.parameters

(Parameter containing:
 tensor([[0.1788, 0.1694]], requires_grad=True),
 Parameter containing:
 tensor([0.4620], requires_grad=True),
 <bound method Module.parameters of Linear(in_features=2, out_features=1, bias=True)>)

In [6]:
import torch
import torch.nn as nn

class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(2, 10)
        self.softmax = nn.Softmax()
        #self.fc2 = nn.Linear(2, 1)

    def forward(self, x):
        x = torch.view(x, -1)
        x = self.fc1(x)
        x = self.softmax(x)
        #x = torch.sigmoid(x)
        #x = torch.sigmoid(self.fc2(x))
        return x

In [7]:
model = SimpleNN()
model

SimpleNN(
  (fc1): Linear(in_features=2, out_features=10, bias=True)
  (softmax): Softmax(dim=None)
)

In [8]:
model(and_data)

AttributeError: module 'torch' has no attribute 'view'

In [ ]:
loss_fn = nn.CrossEntropyLoss()

In [ ]:
import torch.optim as optim

optimizer = optim.Adam(model.parameters(), lr=1e-3)

In [ ]:
model = SimpleNN()


In [ ]:
loss_fn = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

for epoch in range(500):
    optimizer.zero_grad()
    outputs = model(and_data)
    loss = loss_fn(outputs, and_labels)
    print('loss', loss)
    loss.backward()
    optimizer.step()

In [ ]:
model(and_data)

In [ ]:
import matplotlib.pyplot as plt

x1 = [0, 0, 1]
y1 = [0, 1, 0]
x2 = [1]
y2 = [1]

fig, ax = plt.subplots()

ax.scatter(x1, y1)
ax.scatter(x2, y2)
ax.plot(x3, y3)
ax.set_xlim(-0.2, 1.2)
ax.set_ylim(-0.2, 1.2)